import type { ReactNode } from 'react';
import { Droplet, Droplets, Flame, Sun, Thermometer, Wind } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useApp } from '@/state/AppContext';
import { effectiveRainfall, referenceEt0 } from '@/engine/water';
import { ForecastChart } from '@/components/charts';
import { Badge, Callout, Card, SectionHeading, StatCard } from '@/components/ui';

/**
 * Weather intelligence.
 *
 * The forecast is generated by the simulation layer (src/data/weather.ts) and is
 * the SAME series the decision engine consumes — this page is not a decorative
 * widget. The last card documents exactly which forecast fields feed which part
 * of the water/energy calculation.
 */
export default function Weather() {
  const { forecast, conditions, language, recommendation, farm, inputs, dataMode, liveStatus } = useApp();
  const today = forecast[0];
  const hi = language === 'hi';
  const isLive = dataMode === 'live' && liveStatus != null && !liveStatus.degradedToSimulated;

  const et0 = referenceEt0(conditions.temperature, conditions.humidity, conditions.solarAvailability);
  const effRain = effectiveRainfall(conditions.rainfallForecast, conditions.rainProbability);
  const heatDays = forecast.filter((d) => d.isHeatwave || d.temperature >= 38).length;
  const dryDays = forecast.filter((d) => d.rainProbability < 30 && d.rainfall < 1).length;
  const totalRain = forecast.reduce((s, d) => s + d.rainfall, 0);

  return (
    <div>
      <SectionHeading
        eyebrow={hi ? 'मौसम बुद्धिमत्ता' : 'Weather intelligence'}
        title={hi ? 'मौसम' : 'Weather'}
        description={
          hi
            ? 'यह पूर्वानुमान सिंचाई इंजन को सीधे खिलाया जाता है — यह कोई अलग पेज नहीं है।'
            : 'This forecast feeds the irrigation engine directly — it is not a disconnected page.'
        }
      />

      <div className="mb-5 flex flex-wrap items-center gap-2">
        {isLive ? (
          <Badge tone="leaf">🛰️ {hi ? 'लाइव डेटा · Open-Meteo' : 'Live data · Open-Meteo'}</Badge>
        ) : (
          <Badge tone="solar">{hi ? 'सिमुलेटेड डेटा' : 'Simulated data'}</Badge>
        )}
        {isLive && liveStatus && (
          <span className="text-xs text-soil-500">
            {liveStatus.condition} · {liveStatus.resolvedLocation} · {new Date(liveStatus.fetchedAt).toLocaleTimeString()}
          </span>
        )}
        {!isLive && (
          <span className="text-xs text-soil-500">
            {hi
              ? dataMode === 'live'
                ? 'लाइव अनुरोध विफल — निर्धारित सिमुलेशन सक्रिय है।'
                : 'मौसम अमूर्त परत (src/data/weather.ts) से निर्धारित रूप से उत्पन्न। Settings → डेटा स्रोत से लाइव करें।'
              : dataMode === 'live'
                ? 'Live fetch failed — the deterministic simulation is active.'
                : 'Generated deterministically by the weather abstraction layer. Switch to live data in Settings → Data source.'}
          </span>
        )}
      </div>

      {/* Current */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        <StatCard label={hi ? 'तापमान' : 'Temperature'} value={`${today.temperature}°C`} hint={`${today.tempMin}–${today.tempMax}°C`} tone="solar" icon={<Thermometer size={15} />} />
        <StatCard label={hi ? 'आर्द्रता' : 'Humidity'} value={`${today.humidity}%`} tone="sky" icon={<Wind size={15} />} />
        <StatCard label={hi ? 'बारिश संभावना' : 'Rain probability'} value={`${today.rainProbability}%`} hint={hi ? `~${totalRain.toFixed(0)} mm / ${forecast.length} d` : `~${totalRain.toFixed(0)} mm over ${forecast.length} d`} tone={today.rainProbability >= 55 ? 'sky' : 'soil'} icon={<Droplets size={15} />} />
        <StatCard label={hi ? 'वर्षा पूर्वानुमान' : 'Rainfall forecast'} value={`${today.rainfall} mm`} hint={`${hi ? 'प्रभावी' : 'effective'} ${effRain} mm`} tone="sky" icon={<Droplet size={15} />} />
        <StatCard label={hi ? 'सौर उपलब्धता' : 'Solar availability'} value={`${Math.round(today.solarAvailability * 100)}%`} tone="solar" icon={<Sun size={15} />} />
      </div>

      <div className="mt-5 grid gap-5 xl:grid-cols-[1.3fr_1fr]">
        <Card title={hi ? '7-दिन पूर्वानुमान' : '7-day forecast'} subtitle={`${farm.village}, ${farm.district}`}>
          <ForecastChart days={forecast} />
          <div className="mt-4 overflow-x-auto">
            <table className="w-full min-w-[560px] text-sm">
              <thead>
                <tr className="text-left text-xs uppercase tracking-wide text-soil-500">
                  <th className="py-2">{hi ? 'दिन' : 'Day'}</th>
                  <th className="py-2">{hi ? 'ताप' : 'Temp'}</th>
                  <th className="py-2">{hi ? 'आर्द्रता' : 'Humidity'}</th>
                  <th className="py-2">{hi ? 'बारिश' : 'Rain'}</th>
                  <th className="py-2">{hi ? 'मिमी' : 'mm'}</th>
                  <th className="py-2">{hi ? 'सौर' : 'Solar'}</th>
                  <th className="py-2">{hi ? 'सिंचाई' : 'Irrigation'}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-soil-100">
                {forecast.map((d, i) => (
                  <tr key={d.date}>
                    <td className="py-2.5 font-medium text-soil-900">
                      {i === 0 ? (hi ? 'आज' : 'Today') : new Date(d.date).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric' })}
                    </td>
                    <td className="py-2.5 tabular-nums text-soil-700">{Math.round(d.tempMin)}–{Math.round(d.tempMax)}°C</td>
                    <td className="py-2.5 tabular-nums text-soil-700">{d.humidity}%</td>
                    <td className="py-2.5 tabular-nums text-soil-700">{d.rainProbability}%</td>
                    <td className="py-2.5 tabular-nums text-soil-700">{d.rainfall}</td>
                    <td className="py-2.5 tabular-nums text-soil-700">{Math.round(d.solarAvailability * 100)}%</td>
                    <td className="py-2.5">
                      <Badge tone={d.rainProbability >= 55 ? 'sky' : d.rainProbability < 30 ? 'leaf' : 'soil'}>
                        {d.rainProbability >= 55 ? (hi ? 'रुकें' : 'Skip') : d.rainProbability < 30 ? (hi ? 'संभावित' : 'Likely') : (hi ? 'देखें' : 'Watch')}
                      </Badge>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        <div className="space-y-5">
          <Card title={hi ? 'जोखिम रडार' : 'Risk radar'}>
            <div className="space-y-3">
              <RiskRow
                icon={<Flame size={15} />}
                title={hi ? 'गर्मी जोखिम' : 'Heat risk'}
                metric={`${heatDays}/${forecast.length} ${hi ? 'दिन ≥38°C' : 'days ≥38°C'}`}
                note={
                  heatDays > 0
                    ? hi
                      ? 'ऊँचे तापमान से वाष्पोत्सर्जन और फसल जल तनाव बढ़ेगा।'
                      : 'High temperature increases evapotranspiration and crop water stress.'
                    : hi
                      ? 'कोई गंभीर गर्मी पूर्वानुमान नहीं।'
                      : 'No severe heat forecast in this window.'
                }
                tone={heatDays > 0 ? 'danger' : 'leaf'}
              />
              <RiskRow
                icon={<Droplet size={15} />}
                title={hi ? 'सूखा दौर जोखिम' : 'Dry-spell risk'}
                metric={`${dryDays}/${forecast.length} ${hi ? 'सूखे दिन' : 'dry days'}`}
                note={
                  dryDays >= 3
                    ? hi
                      ? 'सिंचाई आवश्यकता की समीक्षा करें; ऑप्टिमाइज़र से अगला विंडो लें।'
                      : 'Review the irrigation requirement and take the next window from the optimizer.'
                    : hi
                      ? 'सूखे दिनों की संख्या कम है।'
                      : 'Few dry days in this window.'
                }
                tone={dryDays >= 3 ? 'solar' : 'leaf'}
              />
              <RiskRow
                icon={<Sun size={15} />}
                title={hi ? 'वर्षा जोखिम' : 'Rainfall risk'}
                metric={`${forecast.filter((d) => d.rainProbability >= 75).length} ${hi ? 'दिन ≥75%' : 'days ≥75%'}`}
                note={
                  forecast.some((d) => d.rainProbability >= 75)
                    ? hi
                      ? 'सिंचाई टाली जा सकती है; जड़ क्षेत्र पहले से भरा हो सकता है।'
                      : 'Irrigation can be delayed — the root zone may already be topped up.'
                    : hi
                      ? 'उल्लेखनीय वर्षा की संभावना नहीं।'
                      : 'No significant rainfall expected.'
                }
                tone={forecast.some((d) => d.rainProbability >= 75) ? 'sky' : 'leaf'}
              />
            </div>
          </Card>

          <Card title={hi ? 'मौसम इंजन को कैसे खिलाता है' : 'How weather feeds the engine'}>
            <ul className="space-y-2.5 text-sm text-soil-600">
              <li className="rounded-lg bg-soil-50 p-3">
                <span className="font-medium text-soil-800">temperature + humidity + solar → ET0</span>
                <br />
                {hi ? `सरलीकृत हारग्रीव्स: ${et0} mm/day` : `Simplified Hargreaves → ET0 = ${et0} mm/day`}
              </li>
              <li className="rounded-lg bg-soil-50 p-3">
                <span className="font-medium text-soil-800">rainfallForecast × rainProbability → effective rainfall</span>
                <br />
                {hi ? `${effRain} mm को फसल की मांग से घटाया जाता है` : `${effRain} mm deducted from crop demand`}
              </li>
              <li className="rounded-lg bg-soil-50 p-3">
                <span className="font-medium text-soil-800">solarAvailability → pump window</span>
                <br />
                {recommendation
                  ? `${hi ? 'वर्तमान विंडो' : 'Current window'}: ${recommendation.recommendedTime}`
                  : '—'}
              </li>
              <li className="rounded-lg bg-soil-50 p-3">
                <span className="font-medium text-soil-800">forecast stability → confidence</span>
                <br />
                {recommendation
                  ? `${hi ? 'विश्वास' : 'Confidence'} ${Math.round(recommendation.confidence * 100)}%`
                  : '—'}
              </li>
            </ul>
            <Link to="/optimizer" className="kf-btn-secondary mt-4">
              {hi ? 'ऑप्टिमाइज़र देखें' : 'Open the optimizer'}
            </Link>
          </Card>

          <Callout tone="solar" title="Prototype simulation — field validation required.">
            {hi
              ? isLive
                ? 'वर्तमान में Open-Meteo से लाइव डेटा; पायलट में IMD जैसे प्रदाता पर स्विच किया जा सकता है।'
                : 'मौसम डेटा सिमुलेटेड है। Settings → डेटा स्रोत से Open-Meteo लाइव डेटा सक्षम करें (कोई API कुंजी नहीं)।'
              : isLive
                ? 'Currently showing live Open-Meteo data; a pilot would switch to an IMD-grade provider.'
                : 'Weather data is simulated. Enable live Open-Meteo data in Settings → Data source (no API key needed).'}
          </Callout>
        </div>
      </div>
    </div>
  );
}

function RiskRow({
  icon,
  title,
  metric,
  note,
  tone,
}: {
  icon: ReactNode;
  title: string;
  metric: string;
  note: string;
  tone: 'danger' | 'solar' | 'leaf' | 'sky';
}) {
  const colors = {
    danger: 'bg-red-50 text-red-700 ring-red-200',
    solar: 'bg-solar-400/15 text-solar-600 ring-solar-400/40',
    leaf: 'bg-leaf-50 text-leaf-700 ring-leaf-200',
    sky: 'bg-sky-50 text-sky-500 ring-sky-200',
  }[tone];
  return (
    <div className="flex gap-3 rounded-xl border border-soil-200 p-3">
      <span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ring-1 ${colors}`}>{icon}</span>
      <div className="min-w-0">
        <p className="text-sm font-semibold text-soil-900">
          {title} <span className="ml-1 text-xs font-medium text-soil-500">{metric}</span>
        </p>
        <p className="mt-0.5 text-sm text-soil-600">{note}</p>
      </div>
    </div>
  );
}
